spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: userService
          uri: http://localhost:1039
          predicates:
            - Path=/user/**
        
        - id: productService
          uri: http://localhost:1040
          predicates:
            - Path=/product/**

        - id: orderService
          uri: http://localhost:1041
          predicates:
            - Path=/order/**

        - id: paymentService
          uri: http://localhost:1042
          predicates:
          - Path=/payment/**
